version: '3.9'

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  rabbit_mq_data:
    driver: local
  es_data:
    driver: local

services:

  mysql:
    image: mysql
    ports:
      - 33306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_system_api_production
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "mysql" ]
      interval: 3s
      retries: 10

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 3s
      retries: 10

  rabbit_mq:
    image: rabbitmq:3-management
    ports:
      - 5672
      - 8080:15672
    volumes:
      - rabbit_mq_data:/var/lib/rabbitmq/mnesia/
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 3s
      retries: 10

  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://elastic_search:9200 || exit 1" ]
      interval: 3s
      retries: 10

  web:
    build: .
    restart: always
    ports:
      - 3000:3000
    command: sh -c "sh ./init.sh && rails s -p 3000 -b '0.0.0.0'"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://web:3000/healthcheck || exit 1" ]
      interval: 3s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      elastic_search:
        condition: service_healthy
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - ELASTIC_SEARCH_URL=elastic_search:9200
      - REDIS_HOST=redis://redis:6379
      - RABBITMQ_HOST=rabbit_mq
      - RABBITMQ_PORT=5672
      - CHAT_SYSTEM_API_DATABASE_PASSWORD=root

  sidekiq_cron:
    build: .
    restart: always
    command: bundle exec sidekiq
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_healthy
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - ELASTIC_SEARCH_URL=elastic_search:9200
      - REDIS_HOST=redis://redis:6379
      - RABBITMQ_HOST=rabbit_mq
      - RABBITMQ_PORT=5672
      - CHAT_SYSTEM_API_DATABASE_PASSWORD=root


  sneakers:
    build: .
    restart: always
    command: rake sneakers:run
    depends_on:
      mysql:
        condition: service_healthy
      rabbit_mq:
        condition: service_healthy
      web:
        condition: service_healthy
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - ELASTIC_SEARCH_URL=elastic_search:9200
      - REDIS_HOST=redis://redis:6379
      - RABBITMQ_HOST=rabbit_mq
      - RABBITMQ_PORT=5672
      - CHAT_SYSTEM_API_DATABASE_PASSWORD=root

